### PR TITLE
Drop sub-libraries for HTTP requests

### PR DESCRIPTION
**Pull request by dmikurube**
It has had varieties of retry helper sub-libraries, but indeed, they are used only from a limited number of plugins/entities.

We are giving up to keep them maintained anymore.

### CODE REVIEW

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

For my understanding.

Does it mean embulk-util-retryhelper drop `JAX-RS` and `Jetty`?
Does embulk-util-retryhelper still depend on `JAX-RS` and `Jetty`?

**Comment by dmikurube** [comment]
"embulk-util-retryhelper" does not have any change. "embulk-util-retryhelper" does not have dependencies on JAX-RS nor Jetty.

"embulk-util-retryhelper-jaxrs/jetty92/93/94" are different from "embulk-util-retryhelper".

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for your comment!

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
